# Generated by Django 5.0.10 on 2025-01-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_acrchiveadminviewset_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AcrchiveAdminViewSet",
        ),
    ]
