# Generated by Django 5.0.10 on 2025-03-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_alter_curatedtopicindexpage_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portalstandardpage",
            options={"verbose_name": "Standard Page"},
        ),
    ]
