# Generated by Django 5.2.9 on 2026-02-18 22:24

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_portalstandardpage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curatedtopicindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", 0),
                    ("two_column_block", 2),
                    ("info_box_block", 5),
                    ("footnote_block", 7),
                    ("image_block", 13),
                    ("fellows_block", 18),
                    ("clear_block", 19),
                    ("webfeed", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"group": "Format and Text"},
                    ),
                    1: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"icon": "arrow-right", "label": "New Column"},
                    ),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("new_column", 1)]],
                        {"group": "Format and Text"},
                    ),
                    3: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "ol",
                                "ul",
                                "hr",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Featured Text",
                            "required": True,
                        },
                    ),
                    4: (
                        "streams.blocks.InfoBoxStyleChoiceBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("style_type", 4)]],
                        {"group": "Format and Text"},
                    ),
                    6: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "ol",
                                "ul",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Footnote Text",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6)]],
                        {"group": "Format and Text"},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required when an image is selected (unless marked as decorative). Describe the image and include any visible text.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check if this image is purely decorative (no meaningful content). Decorative images will have empty alt text for screen readers.",
                            "required": False,
                        },
                    ),
                    12: (
                        "streams.blocks.ImageFormatChoiceBlock",
                        (),
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("caption", 9),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                                ("alignment", 12),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("LG", "Large"),
                                ("MD", "Medium"),
                                ("SM", "Small"),
                            ],
                            "label": "Image Size",
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Slug for anchor link. Must not contain spaces.",
                            "max_length": 50,
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    17: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "bold", "italic", "link"],
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("size", 15),
                                ("anchor", 16),
                                ("profile_text", 17),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    19: (
                        "streams.blocks.ClearBlock",
                        (),
                        {"group": "Layout and Images"},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for callout section", "required": False},
                    ),
                    21: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("webfeed_title", 20), ("webfeed_code", 21)]],
                        {"group": "Layout and Images"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", 0),
                    ("two_column_block", 2),
                    ("info_box_block", 5),
                    ("footnote_block", 7),
                    ("image_block", 13),
                    ("fellows_block", 18),
                    ("clear_block", 19),
                    ("webfeed", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"group": "Format and Text"},
                    ),
                    1: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"icon": "arrow-right", "label": "New Column"},
                    ),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("new_column", 1)]],
                        {"group": "Format and Text"},
                    ),
                    3: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "ol",
                                "ul",
                                "hr",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Featured Text",
                            "required": True,
                        },
                    ),
                    4: (
                        "streams.blocks.InfoBoxStyleChoiceBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("style_type", 4)]],
                        {"group": "Format and Text"},
                    ),
                    6: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "ol",
                                "ul",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Footnote Text",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6)]],
                        {"group": "Format and Text"},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required when an image is selected (unless marked as decorative). Describe the image and include any visible text.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check if this image is purely decorative (no meaningful content). Decorative images will have empty alt text for screen readers.",
                            "required": False,
                        },
                    ),
                    12: (
                        "streams.blocks.ImageFormatChoiceBlock",
                        (),
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("caption", 9),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                                ("alignment", 12),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("LG", "Large"),
                                ("MD", "Medium"),
                                ("SM", "Small"),
                            ],
                            "label": "Image Size",
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Slug for anchor link. Must not contain spaces.",
                            "max_length": 50,
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    17: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "bold", "italic", "link"],
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("size", 15),
                                ("anchor", 16),
                                ("profile_text", 17),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    19: (
                        "streams.blocks.ClearBlock",
                        (),
                        {"group": "Layout and Images"},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for callout section", "required": False},
                    ),
                    21: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("webfeed_title", 20), ("webfeed_code", 21)]],
                        {"group": "Layout and Images"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", 0),
                    ("two_column_block", 2),
                    ("info_box_block", 5),
                    ("footnote_block", 7),
                    ("image_block", 13),
                    ("fellows_block", 18),
                    ("clear_block", 19),
                    ("webfeed", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"group": "Format and Text"},
                    ),
                    1: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"icon": "arrow-right", "label": "New Column"},
                    ),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("new_column", 1)]],
                        {"group": "Format and Text"},
                    ),
                    3: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "ol",
                                "ul",
                                "hr",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Featured Text",
                            "required": True,
                        },
                    ),
                    4: (
                        "streams.blocks.InfoBoxStyleChoiceBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("style_type", 4)]],
                        {"group": "Format and Text"},
                    ),
                    6: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "ol",
                                "ul",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Footnote Text",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6)]],
                        {"group": "Format and Text"},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required when an image is selected (unless marked as decorative). Describe the image and include any visible text.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check if this image is purely decorative (no meaningful content). Decorative images will have empty alt text for screen readers.",
                            "required": False,
                        },
                    ),
                    12: (
                        "streams.blocks.ImageFormatChoiceBlock",
                        (),
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("caption", 9),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                                ("alignment", 12),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("LG", "Large"),
                                ("MD", "Medium"),
                                ("SM", "Small"),
                            ],
                            "label": "Image Size",
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Slug for anchor link. Must not contain spaces.",
                            "max_length": 50,
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    17: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "bold", "italic", "link"],
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("size", 15),
                                ("anchor", 16),
                                ("profile_text", 17),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    19: (
                        "streams.blocks.ClearBlock",
                        (),
                        {"group": "Layout and Images"},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for callout section", "required": False},
                    ),
                    21: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("webfeed_title", 20), ("webfeed_code", 21)]],
                        {"group": "Layout and Images"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portalstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", 0),
                    ("two_column_block", 2),
                    ("info_box_block", 5),
                    ("footnote_block", 7),
                    ("image_block", 13),
                    ("fellows_block", 18),
                    ("clear_block", 19),
                    ("webfeed", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"group": "Format and Text"},
                    ),
                    1: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {"icon": "arrow-right", "label": "New Column"},
                    ),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("new_column", 1)]],
                        {"group": "Format and Text"},
                    ),
                    3: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "ol",
                                "ul",
                                "hr",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Featured Text",
                            "required": True,
                        },
                    ),
                    4: (
                        "streams.blocks.InfoBoxStyleChoiceBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("style_type", 4)]],
                        {"group": "Format and Text"},
                    ),
                    6: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "ol",
                                "ul",
                                "italic",
                                "link",
                                "document-link",
                            ],
                            "label": "Footnote Text",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6)]],
                        {"group": "Format and Text"},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required when an image is selected (unless marked as decorative). Describe the image and include any visible text.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check if this image is purely decorative (no meaningful content). Decorative images will have empty alt text for screen readers.",
                            "required": False,
                        },
                    ),
                    12: (
                        "streams.blocks.ImageFormatChoiceBlock",
                        (),
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("caption", 9),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                                ("alignment", 12),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("LG", "Large"),
                                ("MD", "Medium"),
                                ("SM", "Small"),
                            ],
                            "label": "Image Size",
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Slug for anchor link. Must not contain spaces.",
                            "max_length": 50,
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    17: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "bold", "italic", "link"],
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("size", 15),
                                ("anchor", 16),
                                ("profile_text", 17),
                                ("alt_text", 10),
                                ("is_decorative", 11),
                            ]
                        ],
                        {"group": "Layout and Images"},
                    ),
                    19: (
                        "streams.blocks.ClearBlock",
                        (),
                        {"group": "Layout and Images"},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for callout section", "required": False},
                    ),
                    21: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("webfeed_title", 20), ("webfeed_code", 21)]],
                        {"group": "Layout and Images"},
                    ),
                },
                null=True,
            ),
        ),
    ]
