# Generated by Django 5.2.13 on 2026-07-06 14:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_alter_curatedtopicindexpage_body_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalWagtailifiedPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("richtext", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "streams.blocks.RichtextBlock",
                                (),
                                {"group": "Format and Text"},
                            )
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagtailified Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
