# Generated by Django 5.2.13 on 2026-07-06 14:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_portalwagtailifiedpage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuratedTopicPage2",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Displays underneath the image on the curated topic page                    and as alt text.",
                        max_length=400,
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "byline",
                    models.CharField(
                        blank=True,
                        help_text="Author name, appears below the body.",
                        max_length=200,
                    ),
                ),
                ("search_url", models.URLField(max_length=2000)),
                ("bottom_text", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="A small version of this image will display on the portal                    homepage, and a large version will display at the top of                    each curated topic page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
