# Generated by Django 5.2.13 on 2026-07-06 15:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_curatedtopicpage2"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalhomepage",
            name="introduction2",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
