# Generated by Django 5.2.13 on 2026-07-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_portalhomepage_introduction2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portalwagtailifiedpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="portalhomepage",
            name="introduction2",
        ),
        migrations.DeleteModel(
            name="CuratedTopicPage2",
        ),
        migrations.DeleteModel(
            name="PortalWagtailifiedPage",
        ),
    ]
