# Generated by Django 5.2.13 on 2026-07-09 19:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_remove_portalwagtailifiedpage_page_ptr_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagtailifiedPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("repository", models.CharField(max_length=255)),
                ("date_range", models.CharField(max_length=255)),
                ("historical_note", wagtail.fields.RichTextField(blank=True)),
                ("scope_contents", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
