# Generated by Django 5.2.13 on 2026-07-14 18:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_wagtailifiedpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="abstract",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="conditions_governing_use",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="indexed_terms",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="language",
            field=models.CharField(blank=True, default="English", max_length=100),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="predominant_dates",
            field=models.CharField(
                blank=True, help_text='e.g. "Bulk, 1961-1963"', max_length=255
            ),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="processing_information",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="related_archival_materials",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="size",
            field=models.CharField(
                blank=True, help_text='e.g. "0.4 Linear feet"', max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="date_range",
            field=models.CharField(
                help_text='e.g. "1870-1992, bulk dates 1961-1963"', max_length=255
            ),
        ),
    ]
