# Generated by Django 5.2.13 on 2026-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_wagtailifiedpage_abstract_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wagtailifiedpage",
            old_name="scope_contents",
            new_name="scope_and_contents",
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="date_range",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="predominant_dates",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="size",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
