# Generated by Django 5.2.13 on 2026-07-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0018_rename_scope_contents_wagtailifiedpage_scope_and_contents_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtailifiedpage",
            name="historical_note",
        ),
    ]
