# Generated by Django 5.2.13 on 2026-07-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0019_remove_wagtailifiedpage_historical_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="archive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.archive",
            ),
        ),
    ]
