# Generated by Django 5.2.13 on 2026-08-04 20:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0020_wagtailifiedpage_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="conditions_governing_access",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="date_range",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="repository",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
