# Generated by Django 5.2.13 on 2026-08-06 15:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0021_wagtailifiedpage_conditions_governing_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailifiedpage",
            name="historical_note",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="date_range",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="identifier",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="wagtailifiedpage",
            name="repository",
            field=models.CharField(max_length=255),
        ),
    ]
