# Generated by Django 5.2.13 on 2026-08-13 19:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0022_wagtailifiedpage_historical_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingAidComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("level", models.CharField(blank=True, max_length=50)),
                ("unitid", models.CharField(blank=True, max_length=255)),
                ("unittitle", models.CharField(blank=True, max_length=500)),
                ("unitdate", models.CharField(blank=True, max_length=255)),
                ("extent", models.CharField(blank=True, max_length=255)),
                ("scope_and_contents", wagtail.fields.RichTextField(blank=True)),
                ("container_type", models.CharField(blank=True, max_length=100)),
                ("container_number", models.CharField(blank=True, max_length=100)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="portal.wagtailifiedpage",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="portal.findingaidcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
