# Generated by Django 2.2.6 on 2019-10-24 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstorypage',
            name='story_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='If you use Settings to publish a future post, put the publish date here. Otherwise, leave today as the story date.'),
        ),
        migrations.AlterField(
            model_name='newsstorypage',
            name='lead_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
