# Generated by Django 2.2.6 on 2019-10-24 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191024_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstorypage',
            name='story_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Defaults to date page was created. If you plan to publish in the future post, change to publish date here.'),
        ),
    ]
