# Generated by Django 3.2.11 on 2022-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memb_collections', '0002_auto_20191204_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
