# Generated by Django 4.1.12 on 2025-01-14 21:22

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('memb_collections', '0004_alter_membcollectionindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membcollectionindexpage',
            name='body',
            field=wagtail.fields.StreamField([('richtext', streams.blocks.RichtextBlock()), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', streams.blocks.RichtextBlock(features=['bold', 'italic', 'link'], label='Caption', required=False)), ('alignment', streams.blocks.ImageFormatChoiceBlock(required=False))])), ('new_row', wagtail.blocks.StructBlock([])), ('memb_coll_search_block', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(help_text='Optional: Label placed above search box', required=False)), ('search_help_text', wagtail.blocks.CharBlock(help_text='Optional: Placed below search box', required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
