# Generated by Django 5.2.9 on 2026-02-18 22:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memb_collections", "0005_alter_membcollectionindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membcollectionindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", 0),
                    ("image_block", 6),
                    ("new_row", 7),
                    ("memb_coll_search_block", 10),
                ],
                blank=True,
                block_lookup={
                    0: ("streams.blocks.RichtextBlock", (), {}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: (
                        "streams.blocks.RichtextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Required when an image is selected (unless marked as decorative). Describe the image and include any visible text.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check if this image is purely decorative (no meaningful content). Decorative images will have empty alt text for screen readers.",
                            "required": False,
                        },
                    ),
                    5: (
                        "streams.blocks.ImageFormatChoiceBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("alt_text", 3),
                                ("is_decorative", 4),
                                ("alignment", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[]], {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Label placed above search box",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Placed below search box",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 8), ("search_help_text", 9)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
