# Generated by Django 2.2.6 on 2019-10-23 20:22

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('richtext', streams.blocks.RichtextBlock()), ('page_callout', wagtail.core.blocks.StructBlock([('callout_title', wagtail.core.blocks.CharBlock(help_text='Title for callout section', required=False)), ('callout_text', streams.blocks.RichtextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], label='Callout Text', required=False)), ('button_link', wagtail.core.blocks.PageChooserBlock(help_text='Where you want the button to go', required=False)), ('button_label', wagtail.core.blocks.CharBlock(help_text='Text that shows up in button', required=False))])), ('new_row', wagtail.core.blocks.StructBlock([])), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', streams.blocks.RichtextBlock(features=['bold', 'italic', 'link'], label='Caption', required=False)), ('alignment', streams.blocks.ImageFormatChoiceBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Standard Page',
                'verbose_name_plural': 'Standard Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
