# Generated by Django 2.2.6 on 2019-10-24 21:10

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20191023_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', streams.blocks.RichtextBlock()), ('page_callout', wagtail.core.blocks.StructBlock([('callout_title', wagtail.core.blocks.CharBlock(help_text='Title for callout section', required=False)), ('callout_text', streams.blocks.RichtextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], label='Callout Text', required=False)), ('button_link', wagtail.core.blocks.PageChooserBlock(help_text='Where you want the button to go', required=False)), ('button_label', wagtail.core.blocks.CharBlock(help_text='Text that shows up in button', required=False))])), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', streams.blocks.RichtextBlock(features=['bold', 'italic', 'link'], label='Caption', required=False)), ('alignment', streams.blocks.ImageFormatChoiceBlock(required=False))])), ('new_row', wagtail.core.blocks.StructBlock([])), ('fellows_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Profile Photo', required=False)), ('profile_text', streams.blocks.RichtextBlock(features=['bold', 'italic', 'link'], label='Profile Text', required=False))]))], blank=True, null=True),
        ),
    ]
