# Generated by Django 2.2.10 on 2020-08-04 19:10

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_auto_20200118_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('richtext', streams.blocks.RichtextBlock(group='Format and Text')), ('two_column_block', wagtail.blocks.StreamBlock([('new_column', streams.blocks.RichtextBlock(icon='arrow-right', label='New Column'))], group='Format and Text')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', streams.blocks.RichtextBlock(features=['bold', 'italic', 'link'], label='Caption', required=False)), ('alignment', streams.blocks.ImageFormatChoiceBlock(required=False))], group='Layout and Images')), ('page_callout', wagtail.blocks.StructBlock([('callout_title', wagtail.blocks.CharBlock(help_text='Title for callout section', required=False)), ('callout_text', streams.blocks.RichtextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], label='Callout Text', required=False)), ('button_link', wagtail.blocks.PageChooserBlock(help_text='Where you want the button to go', required=False)), ('button_label', wagtail.blocks.CharBlock(help_text='Text that shows up in button', required=False))], group='Layout and Images')), ('fellows_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Profile Photo', required=False)), ('profile_text', streams.blocks.RichtextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], label='Profile Text', required=False))], group='Layout and Images'))], blank=True, null=True),
        ),
    ]
