# Generated by Django 5.0.10 on 2025-02-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0013_alter_standardpage_body"),
        ("wagtailcore", "0094_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheatsheetPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
