# Generated by Django 5.0.10 on 2025-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0013_alter_standardpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="nested_children_depth",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of levels deep to show child pages (1 means immediate children only).",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="show_nested_children",
            field=models.BooleanField(
                default=False, help_text="Check this to display nested child pages."
            ),
        ),
    ]
