# Generated by Django 2.2.6 on 2019-10-22 19:53

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191022_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecarouselimages',
            old_name='carousel_button',
            new_name='button_link',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('richtext', streams.blocks.RichtextBlock()), ('page_callout', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title for section', required=False)), ('callout_text', streams.blocks.RichtextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], required=False)), ('button_link', wagtail.blocks.PageChooserBlock(required=False)), ('button_label', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
