# Generated by Django 3.2.11 on 2022-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191023_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
