# Generated by Django 5.0.10 on 2025-03-25 17:14

import django.db.models.deletion
import modelcluster.fields
import streams.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_homepage_banner_button_link_and_more"),
        # ("wagtailcore", "0094_query_searchpromotion_querydailyhits"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_button_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Page to which the banner button will link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_button_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the banner button",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_paragraph",
            field=models.TextField(
                blank=True,
                help_text="A short paragraph for the banner above the footer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                blank=True,
                help_text="Title for the banner displayed above the footer.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlight_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for the Highlight Section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlight_button_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Page to which the banner button will link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlight_button_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the banner button",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlight_paragraph",
            field=models.TextField(
                blank=True,
                help_text="A short paragraph for the banner above the footer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="highlight_title",
            field=models.CharField(
                blank=True,
                help_text="Title for the banner displayed above the footer.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", streams.blocks.RichtextBlock()),
                    (
                        "page_callout",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "callout_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title for callout section",
                                        required=False,
                                    ),
                                ),
                                (
                                    "callout_text",
                                    streams.blocks.RichtextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        label="Callout Text",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Where you want the button to go",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text that shows up in button",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "webfeed",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "webfeed_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title for callout section",
                                        required=False,
                                    ),
                                ),
                                (
                                    "webfeed_code",
                                    wagtail.blocks.RawHTMLBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="Main content area of the home page. Add various types of blocks here. It is advisable to keep short form content here, possibly linking to longer content elsewhere, like a news story.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AboutSectionShortcut",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "small_text",
                    models.CharField(
                        blank=True,
                        help_text="Small text for the button in the About Section.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "big_text",
                    models.CharField(
                        blank=True,
                        help_text="Big text for the button in the About Section.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for the button in the About Section.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link for the button in the About Section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_section_shortcut",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
