# Generated by Django 5.0.10 on 2025-03-25 17:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homepage_about_button_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="highlight_title",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Title for the banner displayed above the footer. Supports bold text but makes it blue.",
                null=True,
            ),
        ),
    ]
