# Generated by Django 5.0.10 on 2025-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_homepage_highlight_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepagecarouselimages",
            old_name="carousel_image",
            new_name="banner_option_image",
        ),
        migrations.RenameField(
            model_name="homepagecarouselimages",
            old_name="carousel_text",
            new_name="banner_option_text",
        ),
        migrations.RenameField(
            model_name="homepagecarouselimages",
            old_name="carousel_title",
            new_name="banner_option_title",
        ),
    ]
