# Generated by Django 5.2.6 on 2025-11-26 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0014_rename_carousel_image_homepagecarouselimages_banner_option_image_and_more",
        ),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the image and include ALL text visible in the image for accessibility. Screen reader users rely on this description.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_desktop_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Wide banner image for desktop (recommended: 1200px or wider). Either desktop or mobile image is required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_link_url",
            field=models.URLField(
                blank=True,
                help_text="The URL where users will be directed when they click the banner.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_mobile_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Square banner image for mobile, around 400px, typically used for social media. If not provided, the desktop image will be used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_show",
            field=models.BooleanField(
                default=False,
                help_text="Check to display the promotional banner on the home page.",
            ),
        ),
    ]
