# Generated by Django 5.2.6 on 2025-12-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_homepage_promo_banner_alt_text_and_more"),
        # ("wagtailcore", "0094_alter_page_locale"), # Removed - forces migration ordering that breaks fresh builds (home/0002)
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="promo_banner_link_url",
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_external_url",
            field=models.URLField(
                blank=True,
                help_text="External URL (e.g., https://example.com). If provided, this overrides the page link above.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_link_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an internal page to link to. If external URL is provided below, it will override this.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_banner_alt_text",
            field=models.TextField(
                blank=True,
                help_text="Include ALL TEXT visible in the image (and describe the image if relevant) for accessibility and SEO. Screen reader users rely on this description.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_banner_desktop_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Wide banner image for desktop (recommended: 1200 x 420 px). Either desktop or mobile image is required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_banner_mobile_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Banner image for mobile (recommended: square 600px), typically the same used for social media. Either desktop or mobile image is required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_banner_show",
            field=models.BooleanField(
                default=False,
                help_text="Check to display the promotional banner on the home page. At least one image, alt text, and a link are also required to show the banner.",
            ),
        ),
    ]
