# Generated by Django 5.2.9 on 2026-02-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_homepage_promo_banner_link_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="promo_banner_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Optional. Banner stops displaying after this date (site local date). Leave blank for no expiry.",
                null=True,
            ),
        ),
    ]
