# Generated by Django 2.2.15 on 2020-08-14 17:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False, help_text='Checking this box will enable the alert on all web pages.')),
                ('alert_message', wagtail.core.fields.RichTextField(blank=True, help_text='Alert Message', null=True)),
                ('alert_level', models.CharField(choices=[('alert-info', 'Informational Alert'), ('alert-low', 'General Alert'), ('alert-high', 'Critical Alert')], default='alert-info', max_length=25)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
