# Generated by Django 3.2.11 on 2022-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alertbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertbanner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
