# Generated by Django 5.2.13 on 2026-07-17 18:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_auto_20220118_2043"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainNavigation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "menus",
                    wagtail.fields.StreamField(
                        [("dropdown", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text shown for the dropdown toggle.",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Optional link for the dropdown toggle itself. Takes precedence over URL.",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional manual URL for the dropdown toggle. Used only when no page is set.",
                                    "label": "URL",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text shown for the link.",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to an internal page. Takes precedence over URL.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Manual or external URL. Used only when no page is set. Accepts absolute paths (e.g. /about/) and full URLs.",
                                    "label": "URL",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("page", 4), ("url", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {"label": "Links"}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2), ("items", 7)]],
                                {},
                            ),
                        },
                        help_text="Dropdown menus shown in the main navigation bar. The buttons and search box are not configurable here.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Navigation",
            },
        ),
    ]
