# Generated by Django 5.2.6 on 2025-11-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_auto_20220118_2043"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enable",
                    models.BooleanField(
                        default=False,
                        help_text="Checking this box will enable the promotional banner on the home page.",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Required for accessibility. Describe the image and include ALL text visible in the image. This helps screen reader users understand the promotional content.",
                        max_length=500,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Required. The URL where users will be directed when they click the banner.",
                    ),
                ),
                (
                    "desktop_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The banner image for desktop displays. Recommended width: 1200px or wider.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional banner image optimized for mobile displays. If not provided, the desktop image will be used. Recommended width: 600px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
